# This is a basic workflow to help you get started with Actions

name: CodeCov

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  generate-coverage-report: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: "^3.8"
      - name: Test
        run: bash scripts/test-cov-html.sh
      - name: Upload coverage
        uses: codecov/codecov-action@v2
